baseURL = 'https://kimpham54.github.io/'
languageCode = 'en-us'
title = 'Kim Pham'
theme = "archie"


# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 20 # articles per page


[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	customcss = ["css/first.css"]
	subtitle = 'just some notes'

# Social Tags
[[params.social]]
name = "Email"
icon = "mail"
url = "https://docs.google.com/forms/d/e/1FAIpQLSemLz1deuIX0vN1mFtd0Bh6w_ouyo9bt8k8F4EI1bkf7Ppjnw/viewform"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kimpham54"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/tolloid/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/kim-pham-a9ba8030/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/kimpham54/"

# Main menu Items

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Talks"
url = "/cv"
weight = 2

[[menu.main]]
name = "Work"
url = "/work"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true